#pragma config(Motor,  port2,           bodyRotateMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           armMove,       tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int bound (int max1, int input1, int min1)
{
	// our input is too high
	if (input1 > max1)
	{
		return max1;

		// our input is too low
	}else if (input1 < min1)
	{
		return min1;

		//our input is within bounds
	}else
	{
		return input1;
	}
}

int parabolic(int readJoy, int gain, int maxval)
{
	int parabolicValue;

	//Algorithm:
	//parabolicValue = ((((gain * readJoy) / 100)^2)*(1/maxval));

	parabolicValue = ((gain * readJoy) / 100);
	parabolicValue = (parabolicValue * parabolicValue);
	parabolicValue = (parabolicValue/maxval);

	// Adjust the sign (if readJoy is a negative)
	if (readJoy < 0) {
		parabolicValue *=-1;
	}

	return(parabolicValue);
}


void rotateBody()
{
	int readJoy_x; // will hold the X value of the analog stick
	int joy_x; // will hold the X value after being applied to the parabolic scale
	int gain_x = 40; //change this when you change max/min Motor Speed
	int maxMotorSpeed = 50;

	readJoy_x = vexRT[Ch4]; // This is the LEFT analog stick. For RIGHT, change 'Ch4' to 'Ch1'.
	
	if(readJoy_x <8 && readJoy_x > -8){
		joy_x = 0;
	}else if (readJoy_x >= 8){
		joy_x = (readJoy_x*127/50-8);
	}else if (readJoy_x <= -8){
		joy_x = (readJoy_x*127/50+8);
	}
	//joy_x = parabolic(readJoy_x, gain_x, maxMotorSpeed);

	int motorVal = bound(maxMotorSpeed, (joy_x), (-1 * maxMotorSpeed));		//this is an int for easy debugging
	motor[bodyRotateMotor] = motorVal;
}

void armMovee()
{
	int upButton;
	int downButton;
//	int maxMotorSpeed = 50;

	upButton = vexRT[Btn5U];
	downButton = vexRT[Btn5D];
	
	if (upButton == 1 && downButton == 1) {
		motor [armMove] = 0;		
	}
	else if (upButton == 1) {
		downButton = 0;
		motor [armMove] = 127;
	}
	else if (downButton == 1) {
		upButton = 0;
		motor [armMove] = -127;
	}
	else if (upButton == 0 && downButton == 0){
		motor [armMove] = 0;	
	}
}

//	int motorVal = bound(maxMotorSpeed, (joy_y), (-1 * maxMotorSpeed));		//this is an int for easy debugging
//	motor[bodyRotateMotor] = motorVal;


task main ()
{
	//init();
	while(true) // infinite loop, to keep the program alive
	{
		rotateBody();
		armMovee();
		//rotateClaw();
		//toggleClaw();
	}
}
